### ISSUE TITLE
Uninstallation guide

### ISSUE THREAD

**Issue by ThSGM** [2KAbhishek/Winfiles#3]
### Description of the bug

Hi, thank you for developing these scripts. I am still learning the whole procedure.

Please can you provide some notes on how to uninstall (or revert) the changes that were introduced by the installer script? 

### Steps To Reproduce

1. Install the script
2. Try to uninstall all the different changes

**Comment by 2KAbhishek** [comment]
The best way to do so will be uninstalling the scoop packages and then removing the symlinks created by `setup.ps1`

I don't have a detailed uninstall script handy, you can go through the commands in that file and manually uninstall things no longer needed.

Hope that helps
